### PR TITLE
Added TypeScript types for library

### PR DESCRIPTION
**Pull request by idchlife**
Hello! I wanted to add types to this very useful library. There are some improvements may be done to modifiers section, but every other predicate is working. Also with type guards for primitives, which is very handy in TypeScript

### CODE REVIEW

**Comment by philbooth** [comment]
Hey @idchlife, thanks for working on this!

I'm conscious that, being totally unfamiliar with TypeScript, I'm neither qualified to review this or to maintain it post-merge. As such, I wonder if it makes sense for you to keep it as a separate repo and then I can link to it in the readme for people that are interested. Would that work or does it need to be inside this repo for the benefits to take effect in the TS ecosystem?

**Comment by idchlife** [comment]
@philbooth there is of course an option, adding to https://github.com/DefinitelyTyped/DefinitelyTyped repository so it can be installed via npm i @types/check-types.js --save-dev and it's totally ok.

But I wanted to add types here because it's very handy when you install repo and types are already there, because a) you have autocomplete even in non-typescript projects in some modern IDEs (they often check typescript definition files and show clever and nice intellisense) b) you don't have to bother installing types separately, which shows (at least for some people) that library is well maintained etc.

About maintaining types - I added some info with my email and github nickname into the beginning of type files, so it can be used to ping me for improvements etc. I will gladly accept requests to update types files if there is another release with major changes.

About review - I wrote types files first for myself, because I work with TypeScript and your library is very handy and helpful, especially with type definitions.
Basic functionality works nice.

It's your choice of course, I will accept if you would prefer to add types to DefinetelyTyped. They won't arrive that quickly into npm of course, but well, you're the boss! ;)

**Comment by philbooth** [comment]
Okay, in that case I prefer the DefinitelyTyped approach. Leave a comment here when it's done and I'll add a section to the readme so that anyone who wants to pick up the definitions knows where to find them.

**Comment by idchlife** [comment]
@philbooth types are available via npm i @types/check-types --save-dev

**Pull request closed without merging**
